"use client";

import ScrollReveal from "@/components/ScrollReveal";
import PlaceholderBarChart from "@/components/charts/PlaceholderBarChart";

export default function DieselVsElectrifiedSection() {
  return (
    <section className="relative py-32 sm:py-40 bg-background overflow-hidden">
      <div className="max-w-7xl mx-auto px-6">
        <ScrollReveal>
          <div className="text-center max-w-2xl mx-auto mb-20">
            <span className="placeholder-badge mb-6 inline-block">
              Section 04
            </span>
            <h2 className="font-heading text-4xl sm:text-5xl text-primary leading-tight mb-6">
              Diesel vs Electrified Rail
            </h2>
            <p className="font-body text-body/50 text-base">
              Though trains are more efficient than trucks, not all trains are
              equally efficient. The energy source powering rail has massive
              implications for cost, emissions, and long-term viability.
            </p>
          </div>
        </ScrollReveal>

        {/* Contrasting two-column layout with a center divider */}
        <div className="relative grid grid-cols-1 lg:grid-cols-2 gap-0">
          {/* Vertical center divider */}
          <div className="hidden lg:block absolute left-1/2 top-0 bottom-0 w-px bg-gradient-to-b from-transparent via-primary/20 to-transparent" />

          {/* Diesel side */}
          <ScrollReveal delay={0.1} direction="left">
            <div className="p-8 sm:p-12 lg:pr-16">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-full bg-body/10 flex items-center justify-center">
                  <div className="w-4 h-4 rounded-full border-2 border-body/30" />
                </div>
                <h3 className="font-heading text-2xl text-body">Diesel</h3>
              </div>

              <div className="space-y-6 mb-10">
                <p className="font-body text-body/45 text-sm leading-relaxed">
                  Diesel-powered trains transfer about 30–35% of the
                  energy generated by combustion to the wheels. While diesel
                  fuel prices are currently low, many analysts predict the
                  long-term trend is for those prices to increase.
                </p>
                <p className="font-body text-body/45 text-sm leading-relaxed">
                  Diesel locomotives produce soot, volatile organic compounds,
                  nitrogen oxides, and sulfur oxides—all of which affect
                  public health, especially as many railroads pass through
                  urban areas.
                </p>
              </div>

              {/* Diesel metrics */}
              <div className="space-y-3">
                {[
                  "30–35% energy transfer efficiency",
                  "Higher long-term fuel cost trajectory",
                  "Higher maintenance costs vs. electric",
                ].map((placeholder) => (
                  <div
                    key={placeholder}
                    className="flex items-center gap-3 py-2 border-b border-primary/8"
                  >
                    <div className="w-2 h-2 rounded-full bg-body/20" />
                    <span className="font-body text-xs text-body/40">
                      {placeholder}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </ScrollReveal>

          {/* Electrified side */}
          <ScrollReveal delay={0.2} direction="right">
            <div className="p-8 sm:p-12 lg:pl-16 bg-primary/[0.03]">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-full bg-accent/15 flex items-center justify-center">
                  <div className="w-4 h-4 rounded-full bg-accent/60" />
                </div>
                <h3 className="font-heading text-2xl text-primary">
                  Electrified
                </h3>
              </div>

              <div className="space-y-6 mb-10">
                <p className="font-body text-body/45 text-sm leading-relaxed">
                  Supplying electricity directly from an overhead powerline
                  transfers about 95% of the energy to the wheels. It is
                  estimated to be 50% less expensive to power a train by
                  electricity than by diesel.
                </p>
                <p className="font-body text-body/45 text-sm leading-relaxed">
                  Electric locomotive engines cost about 20% less than diesel
                  on the global market, and maintenance costs are 25–35% lower.
                  India has moved from 45% electrified track in 2015 to 80%
                  in 2022, targeting 100% electrification.
                </p>
              </div>

              {/* Electrified metrics */}
              <div className="space-y-3">
                {[
                  "~95% energy transfer efficiency",
                  "50% less expensive to operate than diesel",
                  "25–35% lower maintenance costs",
                ].map((placeholder) => (
                  <div
                    key={placeholder}
                    className="flex items-center gap-3 py-2 border-b border-accent/15"
                  >
                    <div className="w-2 h-2 rounded-full bg-accent/60" />
                    <span className="font-body text-xs text-body/40">
                      {placeholder}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </ScrollReveal>
        </div>

        {/* U.S. lagging callout */}
        <ScrollReveal delay={0.25}>
          <div className="mt-20 bg-primary text-background p-8 sm:p-12 rounded-sm">
            <div className="max-w-3xl mx-auto text-center">
              <p className="font-heading text-6xl sm:text-7xl text-accent mb-4">
                0.93%
              </p>
              <p className="font-heading text-xl sm:text-2xl text-background/80 mb-3">
                of U.S. rail track is electrified
              </p>
              <p className="font-body text-background/45 text-sm leading-relaxed max-w-xl mx-auto">
                Out of 220,044 km of track, only 2,065 km are electrified.
                The world average is 31%. The EU averages 57%.
                Switzerland, India, and others have reached or are approaching 100%.
              </p>
            </div>
          </div>
        </ScrollReveal>

        {/* Electrification comparison chart */}
        <ScrollReveal delay={0.3}>
          <div className="mt-10 bg-primary/[0.02] border border-primary/10 p-6 sm:p-10 rounded-sm">
            <h3 className="font-heading text-lg text-primary mb-1">
              Rail Electrification by Country (% of Network)
            </h3>
            <p className="font-body text-body/45 text-xs mb-8">
              Data from Wikipedia, sourced from national rail authorities. The
              U.S. ranks among the lowest in the world.
            </p>
            <PlaceholderBarChart
              bars={[
                { label: "Switzerland (100%)", heightPercent: 100, color: "#D4AF37" },
                { label: "India (99.4%)", heightPercent: 99, color: "#D4AF37" },
                { label: "EU Avg (57%)", heightPercent: 57, color: "rgba(212,175,55,0.6)" },
                { label: "China (74%)", heightPercent: 74, color: "rgba(212,175,55,0.5)" },
                { label: "UK (38%)", heightPercent: 38, color: "rgba(27,48,34,0.5)" },
                { label: "World (31%)", heightPercent: 31, color: "rgba(27,48,34,0.4)" },
                { label: "U.S. (0.93%)", heightPercent: 4, color: "#1B3022" },
              ]}
              yAxisLabel="% of track electrified"
              xAxisLabel="Country / Region"
              height={300}
            />
          </div>
        </ScrollReveal>

        {/* Transition to travel time */}
        <ScrollReveal delay={0.35}>
          <div className="mt-20 border-l-2 border-accent pl-6 max-w-3xl">
            <p className="font-body text-body/70 text-base leading-relaxed">
              Emissions aren&rsquo;t the only cost of that gap. Without
              modern electrified infrastructure, American trains are also
              much slower than trains in most other countries.
            </p>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
}
